version: "3.3"

services:
  mongodb:
    ports:
      - ${DATABASE_PORT}:27017
  mongoclient:
    image: mongo-express
    restart: always
    ports:
      - 8017:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_ADMIN_PASSWORD}
