// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Cds.BusinessCustomer.Tests.Bdd.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GetCustomerBySiretFeature : object, Xunit.IClassFixture<GetCustomerBySiretFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetCustomerBySiret.feature"
#line hidden
        
        public GetCustomerBySiretFeature(GetCustomerBySiretFeature.FixtureData fixtureData, Cds_BusinessCustomer_Tests_Bdd_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetCustomerBySiret", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Business Customer by Siret")]
        [Xunit.TraitAttribute("FeatureTitle", "GetCustomerBySiret")]
        [Xunit.TraitAttribute("Description", "Get Business Customer by Siret")]
        [Xunit.TraitAttribute("Category", "BusinessCustomerBySiret")]
        public virtual void GetBusinessCustomerBySiret()
        {
            string[] tagsOfScenario = new string[] {
                    "BusinessCustomerBySiret"};
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Business Customer by Siret", null, new string[] {
                        "BusinessCustomerBySiret"});
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "value"});
                table5.AddRow(new string[] {
                            "name",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table5.AddRow(new string[] {
                            "siret",
                            "81999478100022"});
                table5.AddRow(new string[] {
                            "naf_code",
                            "8299Z"});
                table5.AddRow(new string[] {
                            "zip_code",
                            "33000"});
                table5.AddRow(new string[] {
                            "city",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table5.AddRow(new string[] {
                            "social_reason",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table5.AddRow(new string[] {
                            "phone",
                            "+21268085321"});
                table5.AddRow(new string[] {
                            "Adress",
                            "Maarif"});
                table5.AddRow(new string[] {
                            "Civility",
                            "Marocaine"});
#line 5
 testRunner.Given("a Business Customer with the Siret : \"81999478100022\"  and request to CartegieApi" +
                        " returns :", ((string)(null)), table5, "Given ");
#line hidden
#line 16
 testRunner.When("the Business Customer API receives the get request with Siret : \"81999478100022\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
 testRunner.Then("the response status is : \"200\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "property",
                            "value"});
                table6.AddRow(new string[] {
                            "name",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table6.AddRow(new string[] {
                            "siret",
                            "81999478100022"});
                table6.AddRow(new string[] {
                            "naf_code",
                            "8299Z"});
                table6.AddRow(new string[] {
                            "zip_code",
                            "33000"});
                table6.AddRow(new string[] {
                            "city",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table6.AddRow(new string[] {
                            "social_reason",
                            "UBER PARTNER SUPPORT FRANCE SAS"});
                table6.AddRow(new string[] {
                            "phone",
                            "+21268085321"});
                table6.AddRow(new string[] {
                            "Adress",
                            "Maarif"});
                table6.AddRow(new string[] {
                            "Civility",
                            "Marocaine"});
#line 18
 testRunner.And("the Business Customer API sends business customer information :", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetCustomerBySiretFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetCustomerBySiretFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
